server:
  port: 8080

spring:
  application:
    name: notificartion-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/notification_db}
    username: ${SPRING_DATASOURCE_USERNAME:notification_user}
    password: ${SPRING_DATASOURCE_PASSWORD:notification_password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
